### ISSUE TITLE
Animate card toggle

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#10]
## Value statement

As a **user**
when I **toggle** the details of an item card **I don't want to be confused by sudden changes**

## Description (Text, Scribble, Wireframe, Design)

* When a card is toggled, the details should not just suddenly appear but have a smooth expanding animation.

## Acceptance criteria

* [x] The card expands with a smooth animation when it is toggled
* [x] The details do not appear before the animation is finished

## Tasks

* [x]  Add toggle animation
* [x]  Styling
* [x]  Test in mobile view

## Size

small
