### ISSUE TITLE
Delete item

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#11]
## Value statement

As a **user**
I want to **delete items that I no longer use**

## Description (Text, Scribble, Wireframe, Design)

* In the card details there is a button "delete"
* When the delete button is clicked, the item is deleted and the user is returned to the list screen

## Acceptance criteria

* [ ]  When delete button is clicked, object is deleted from the array and does not appear in the list any more

## Tasks

* [ ]  Add button
* [ ]  Create delete logic
* [ ]  Test on mobile

## Size

small
