### ISSUE TITLE
Send reminder e-mail

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#12]
## Value statement

As a **user**
I **need to remind the borrower when an item is overdue**

## Description (Text, Scribble, Wireframe, Design)

* A "send reminder" button in the card details
* The button appears when the item is overdue
* A modal opens with the reminder text and a "send" button to finally send the reminder and a cancel button

## Acceptance criteria

* [ ] The "send reminder" button is only visible when the item is overdue
* [ ] A modal opens when the "send reminder" button is clicked
* [ ] If the cancel button is clicked, the modal closes without sending the reminder
* [ ] If the "send" button is clicked, the modal closes and the reminder is send via email

## Tasks

* [ ] Create a modal
* [ ] Create function to check the due date for being overdue
* [ ] Create function to sent email with rewritten text
* [ ] Test on mobile

## Size

medium
