### ISSUE TITLE
Edit item

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#13]
## Value statement

As a **user**
I want to **edit items so I an reuse them and lend the to different people**

## Description (Text, Scribble, Wireframe, Design)

* In the card details there is a button "edit"
* When the edit button is clicked, a form opens where I can change the item title, borrower, date and due date

## Acceptance criteria

* [ ]  When edit button is clicked, a modal opens
* [ ] The modal has inputs for item title, borrower, date and due date
* [ ] The modal has a "save" button
* [ ]  The first input has focus at start
* [ ]  The modal is closed after "save" button is clicked
* [ ]  The card is updated with the new inputs

## Tasks

* [ ]  Add button
* [ ]  Create edit logic
* [ ]  Test on mobile

## Size

medium
