### ISSUE TITLE
Throw out the modal!

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#15]
## Value statement

As a **user**
I need **to add new items** to the list **without being distracted by a new page opening**

## Description (Text, Scribble, Wireframe, Design)

* The modal is thrown out of the code! Instead the form is shown es a new card at the beginning of the list.
* The card is hidden by default and toggled to visible with the click on the "Add" button
* When the "submit" button is clicked, the form card is toggled to invisible again and the real new card is created at the beginning of the list

## Acceptance criteria

* [ ]  The form opens as a new empty card at the top of the list
* [ ]  The form reacts on submit (Enter key or button press)
* [ ]  The first input has focus at start
* [ ]  The form is closed after submit
* [ ]  The new card is added at the top

## Tasks

* [ ]  Remove modal functions
* [ ] Create toggle function
* [ ]  Create form component
* [ ]  Add styling
* [ ]  Test on mobile

## Size

large
