### ISSUE TITLE
Refactor handleToggle function

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#18]
## Value statement

Code refactor

## Description (Text, Scribble, Wireframe, Design)

* The handleToggle function is needed in different components and written everytime. This is unnecessary an can be refactored.

## Acceptance criteria

* [ ] The handleToggle function is imported wherever it is needed

## Tasks

* [ ] Move handleToggle function to utils.js
* [ ] Import handleToggle functions where it is called

## Size

small
