### ISSUE TITLE
Toggle Item card details

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#2]
## Value statement

As a **user**
when I **click** on an item card **I want to see details about the item I lend someone**

## Description (Text, Scribble, Wireframe, Design)

* It's a scrolling list of item-cards
* An item-card contains an item title, the person who the user has lend it to, the date it was borrowed and the due date

## Acceptance criteria

* [ ] The item details are hidden by default
* [ ] Each item card expands on click to show the details
* [ ] Expansion is animated

## Tasks

* [ ]  Add toggle logic
* [ ]  Styling
* [ ]  Test in mobile view

## Size

medium
