### ISSUE TITLE
Item becomes "available" without borrower

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#22]
## Value statement

As a **user**
I need to **see which items are currently not lent to anyone**

## Description (Text, Scribble, Wireframe, Design)

* Outgoing and due dates should only be able to be entered when a borrower is entered in the input field
* When an item is saved without a borrower, no empty fields appear in the card. Instead the text "available" appears in green color

## Acceptance criteria

* [ ] When no borrower is entered the user also cannot enter any date
* [ ] When an item is saved without borrower, the text "available" appears instead on the card.

## Tasks

* [ ] Create logic so the date and due date input fields are disabled and their values are cleared when the length of the borrower input is < 1
* [ ] Create toggle logic so the text "available" is shown instead of empty fields when an item is saved withoud borrower

## Size

medium
