### ISSUE TITLE
Create custom hooks

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#24]
## Value statement

Custom hooks are necessary so the Card components can be refactored

## Description (Text, Scribble, Wireframe, Design)

* Create custom hooks for the itemCard component

## Acceptance criteria

* [ ] EditToggle and DetailsToggle are in a custom hook component

## Tasks

* [ ] create hook for DetailsToggle
* [ ] create hook for EditToggle

## Size

medium
