### ISSUE TITLE
Mail Credentials

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#28]
## Value statement

As a **user**
I need **to input my email credentials**

## Description (Text, Scribble, Wireframe, Design)

* A form to input use name and smtp-server credentials
* If no credentials are typed in, no mail reminder buttons will be shown
* A button to save credentials

## Acceptance criteria

* [ ]  The form opens as a modal
* [ ]  The form reacts on button click
* [ ]  The first input has focus at start
* [ ]  The modal is closed after submit
* [ ]  The credentials are saved in local storage

## Tasks

* [ ]  Add modal
* [ ]  Create form component
* [ ]  Add styling
* [ ]  Test on mobile

## Size

small
