### ISSUE TITLE
Save state locally

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#3]
## Value statement

As a **user**
I need to **keep edited information about lent items trough sessions**

## Description (Text, Scribble, Wireframe, Design)

* No visible impact

## Acceptance criteria

* [ ] every change on the state `items` should trigger a save to localStorage
* [ ] Reload of the page should load `items` from localStorage

## Tasks

* [ ]  Create services for localStorage
* [ ]  Test in mobile view

## Size

small
