### ISSUE TITLE
Create new Item

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#4]
## Value statement

As a **user**
I need **to add new items to the list**

## Description (Text, Scribble, Wireframe, Design)

* A form to add cards with inputs for item title and borrower
* If no borrower is typed in, the borrower will be "none" in green color signifying that the item is available
* A button to submit [Create item]

## Acceptance criteria

* [ ]  The form is found at the path "/create"
* [ ]  The button is disabled until both item title is filled
* [ ]  If input "name" is not filled its value is set to the string "none" and the color of the name is set to green
* [ ]  The form reacts on submit (Enter key or button press)
* [ ]  The first input has focus at start and after submit
* [ ]  The form is cleared after submit
* [ ]  The new card is added at the top

## Tasks

* [ ]  Add routing
* [ ]  Create form component
* [ ]  Add styling
* [ ]  Test on mobile

## Size

large
