### ISSUE TITLE
Available items filter

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#5]
## Value statement

As a **user**
I need to **just see which items are either available or currently lent to someone**
so there is **less visual clutter**

## Description (Text, Scribble, Wireframe, Design)

* A small button at the top of the screen saying [All items], [Lent items], and [Available items]

## Acceptance criteria

* [ ] Link text toggles
* [ ] Lent / all items are toggled with link

## Tasks

* [ ]  Create or use a Link (or Button) component
* [ ]  Add state "isOnlyLentShown"

## Size

medium
