### ISSUE TITLE
Search items

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#6]
## Value statement

As a **user**
I sometimes **need to search for a specific item to check it's status**

## Description (Text, Scribble, Wireframe, Design)

* A search input at the top of the screen
* When the search input returns an existing item, only that item will be shown in the list
* When the search input does not exist, no item is shown in the list and the message "not found" is shown instead of an item card

## Acceptance criteria

* [ ] If something is entered in the input field, the item names are filtered down
* [ ] If the filtered items are empty, a message "not found" is shown instead
* [ ] If the input field is cleared, the filter is reset and all items are shown

## Tasks

* [ ] Create a search input component
* [ ] Create a useState for the input field

## Size

medium
