### ISSUE TITLE
Date selector

### ISSUE THREAD

**Issue by normanbos** [normanbos/lendmethis#8]
## Value statement

As a **user**
I need **to select the date and time when something was lent out to someone and when that item is due to return**

## Description (Text, Scribble, Wireframe, Design)

* The calendar should be accessible thorugh the "create" page
* A button or link that will open a calendar where the user set dates by clicking on them
* If no borrower is put in then the calendar button is disabled
* A button to save that selected dates
* When the save button is clicked, that calendar should close and return to the "create" page

## Acceptance criteria

* [ ]  The calendar button is disabled until the input field "borrower" is filled
* [ ]  The due date cannot be in the past
* [ ]  The item card is updated with the respective dates

## Tasks

* [ ]  Add google calendar API
* [ ]  Create calendar component
* [ ]  Add styling
* [ ]  Test on mobile

## Size

large
